_wandb:
    value:
        cli_version: 0.23.0
        e:
            85xqtqdbsf6lrwt9ew6il0nx22mc4slj:
                args:
                    - --model_path_splatpose
                    - /home/wangyifa/tmp/3dfm4anomaly_detection/scripts/test_MAD_Sim_improve_splatpose_inference_process/3dgs_model
                    - --data_path
                    - /home/wangyifa/tmp/3dfm4anomaly_detection/data/MAD-Sim
                    - --result
                    - /home/wangyifa/tmp/3dfm4anomaly_detection/scripts/test_MAD_Sim_improve_splatpose_inference_process/ad_result
                    - --classname
                    - 01Gorilla
                    - --prefix
                    - improve
                    - -k
                    - "150"
                codePath: demo_splatpose_pipeline.py
                codePathLocal: demo_splatpose_pipeline.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "105089261568"
                        used: "69503750144"
                email: 1356322400@qq.com
                executable: /home/wangyifa/anaconda3/tmp/miniconda3/envs/3d-model-ampere-cuda12.9/bin/python
                git:
                    commit: 1c143eae19c99fca8bd20431841f69bb39a77518
                    remote: git@github.com:sIHURs/3dfm4anomaly_detection.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-1a9540ae-2404-e518-cd5f-395bb83a507b
                host: capybara.tnt.uni-hannover.de
                memory:
                    total: "67153317888"
                os: Linux-6.4.0-150600.23.53-default-x86_64-with-glibc2.38
                program: /home/wangyifa/tmp/3dfm4anomaly_detection/demo_splatpose_pipeline.py
                python: CPython 3.11.14
                root: /home/wangyifa/tmp/3dfm4anomaly_detection
                startedAt: "2026-01-06T11:29:34.945735Z"
                writerId: 85xqtqdbsf6lrwt9ew6il0nx22mc4slj
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 79
                - 105
            "2":
                - 1
                - 5
                - 41
                - 53
                - 79
                - 105
            "3":
                - 16
            "4": 3.11.14
            "5": 0.23.0
            "12": 0.23.0
            "13": linux-x86_64
classname:
    value: 01Gorilla
data_path:
    value: /home/wangyifa/tmp/3dfm4anomaly_detection/data/MAD-Sim
gauss_iters:
    value: 30000
json_name:
    value: transforms.json
k:
    value: 150
loftr_batch:
    value: 32
loftr_resolution:
    value:
        - 128
        - 128
model_path_splatpose:
    value: /home/wangyifa/tmp/3dfm4anomaly_detection/scripts/test_MAD_Sim_improve_splatpose_inference_process/3dgs_model
pcd_name:
    value: point_cloud.ply
prefix:
    value: improve
result:
    value: /home/wangyifa/tmp/3dfm4anomaly_detection/scripts/test_MAD_Sim_improve_splatpose_inference_process/ad_result
seed:
    value: 0
use_wandb:
    value: 1
verbose:
    value: 0
wandb:
    value: 1
